#!/usr/bin/env python3
"""
Generate a synthetic fluorescence-microscope-style WebP dataset
for the Virtual Microscope app.

Output layout (matches public/manifest.json):
    public/assets/zoom_00/z_000.webp
    public/assets/zoom_00/z_001.webp
    ...
    public/assets/zoom_49/z_049.webp

Each frame is a 512×512 8-bit image with:
    - One synthetic scene containing several irregular fluorescent-like blobs
    - Progressive zoom generated by cropping tighter around the image centre for each zoom level
    - Slice blur that increases with slice index (z_000 sharpest -> z_max blurriest)

Requirements: Python 3.9+, Pillow (pip install Pillow)
Optional:     numpy (faster), but the script works with pure Pillow too.

Usage:
    python scripts/generate_test_data.py            # writes to public/assets/
    python scripts/generate_test_data.py --outdir /tmp/test_assets
    python scripts/generate_test_data.py --zooms 10 --slices 10  # smaller set for quick tests
"""

from __future__ import annotations

import argparse
import math
import random
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit("Pillow is required.  Install it with:  pip install Pillow")


# --------------- constants / defaults ---------------

WIDTH = 512
HEIGHT = 512
DEFAULT_ZOOMS = 50
DEFAULT_SLICES = 50
SEED = 42
SCENE_SIZE = 2048
MAX_SLICE_BLUR = 6.0
MIN_CROP_SIZE = 48
BLOB_COUNT = 12


# --------------- helpers ---------------

def draw_irregular_blob(
    draw: ImageDraw.ImageDraw,
    rng: random.Random,
    center: tuple[int, int],
    base_radius: float,
    points: int,
    intensity: int,
) -> None:
    """Draw one non-circular blob as a jittered radial polygon."""
    cx, cy = center
    vertices: list[tuple[float, float]] = []
    for i in range(points):
        ang = (2.0 * math.pi * i / points) + rng.uniform(-0.16, 0.16)
        rad = base_radius * rng.uniform(0.65, 1.35)
        x = cx + math.cos(ang) * rad
        y = cy + math.sin(ang) * rad
        vertices.append((x, y))
    draw.polygon(vertices, fill=intensity)


def make_base_scene(rng: random.Random, scene_size: int = SCENE_SIZE) -> Image.Image:
    """Create one synthetic scene with multiple irregular blobs near the centre."""
    noise = Image.effect_noise((scene_size, scene_size), 14)
    background = noise.point(lambda p: int(max(0, min(255, 16 + p * 0.22))))
    background = background.filter(ImageFilter.GaussianBlur(radius=1.2))

    draw = ImageDraw.Draw(background)
    cx = scene_size // 2
    cy = scene_size // 2

    for i in range(BLOB_COUNT):
        spread = scene_size * (0.055 if i < 8 else 0.12)
        bx = int(round(cx + rng.uniform(-spread, spread)))
        by = int(round(cy + rng.uniform(-spread, spread)))

        outer_r = rng.uniform(16.0, 34.0)
        inner_r = outer_r * rng.uniform(0.48, 0.62)

        draw_irregular_blob(
            draw,
            rng,
            (bx, by),
            base_radius=outer_r,
            points=rng.randint(8, 13),
            intensity=rng.randint(80, 130),
        )
        draw_irregular_blob(
            draw,
            rng,
            (bx, by),
            base_radius=inner_r,
            points=rng.randint(7, 11),
            intensity=rng.randint(150, 215),
        )

    # Guarantee a clearly visible central object so center-locked zoom stays meaningful.
    draw_irregular_blob(draw, rng, (cx, cy), base_radius=20.0, points=12, intensity=180)
    draw_irregular_blob(draw, rng, (cx, cy), base_radius=10.0, points=10, intensity=238)
    draw_irregular_blob(draw, rng, (cx, cy), base_radius=4.8, points=9, intensity=255)

    background = background.filter(ImageFilter.GaussianBlur(radius=0.6))
    return background


def crop_for_zoom(scene: Image.Image, zoom: int, total_zooms: int, min_crop_size: int = MIN_CROP_SIZE) -> Image.Image:
    """Return a 512x512 crop that progressively zooms into image centre."""
    scene_size = scene.width
    if total_zooms <= 1:
        t = 1.0
    else:
        t = zoom / (total_zooms - 1)

    # Exponential interpolation for a stronger microscope-like zoom progression.
    scale = (min_crop_size / scene_size) ** t
    crop_size = max(min_crop_size, int(round(scene_size * scale)))

    # Keep field-of-view fixed in the centre to avoid lateral movement while zooming.
    left = (scene_size - crop_size) // 2
    top = (scene_size - crop_size) // 2
    right = left + crop_size
    bottom = top + crop_size

    cropped = scene.crop((left, top, right, bottom))
    return cropped.resize((WIDTH, HEIGHT), resample=Image.Resampling.LANCZOS)


def apply_slice_blur(img: Image.Image, focus: int, total_slices: int) -> Image.Image:
    """Increase blur with slice index (low index = sharp, high index = blurrier)."""
    if total_slices <= 1:
        return img
    t = focus / (total_slices - 1)
    radius = t * MAX_SLICE_BLUR
    if radius <= 0:
        return img
    return img.filter(ImageFilter.GaussianBlur(radius=radius))


def colorize_green(gray: Image.Image) -> Image.Image:
    """Convert grayscale to green-channel fluorescence look."""
    zeros = Image.new("L", gray.size, 0)
    return Image.merge("RGB", (zeros, gray, zeros))


# --------------- main ---------------

def generate(outdir: Path, zooms: int, slices: int) -> None:
    rng = random.Random(SEED)
    total_frames = zooms * slices
    generated = 0

    scene = make_base_scene(rng)

    for z in range(zooms):
        zoom_dir = outdir / f"zoom_{z:02d}"
        zoom_dir.mkdir(parents=True, exist_ok=True)

        base = crop_for_zoom(scene, z, zooms)

        for f in range(slices):
            frame = apply_slice_blur(base.copy(), f, slices)
            frame = colorize_green(frame)
            fpath = zoom_dir / f"z_{f:03d}.webp"
            frame.save(fpath, "WEBP", quality=80)
            generated += 1
            if generated % 100 == 0 or generated == total_frames:
                pct = generated / total_frames * 100
                print(f"  [{pct:5.1f}%] {generated}/{total_frames}  →  {fpath}")

    print(f"\nDone — {generated} frames written to {outdir}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate synthetic microscope test data")
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "public" / "assets",
        help="Output directory (default: public/assets/)",
    )
    parser.add_argument("--zooms", type=int, default=DEFAULT_ZOOMS, help="Number of zoom levels")
    parser.add_argument("--slices", type=int, default=DEFAULT_SLICES, help="Number of z-slices")
    args = parser.parse_args()

    print(f"Generating {args.zooms}×{args.slices} = {args.zooms * args.slices} frames "
          f"({WIDTH}×{HEIGHT} WebP) → {args.outdir}")
    generate(args.outdir, args.zooms, args.slices)


if __name__ == "__main__":
    main()
